var ASACodes = {"tp": {
 "Title": "Therapeutic Products",
 "Hint": "e.g. a Medicine or Medical Device",
 "URL": "http://www.asa.co.nz/code_therapeutic_products.php",
 "Introduction": "All advertisements for therapeutic products shall adhere to the Principles and Guidelines set out in this Code. The Code is designed to ensure that advertising for such products will be conducted in a manner which is socially responsible and does not mislead or deceive the consumer. Other ASA Codes may also be relevant. In interpreting the Code emphasis will be placed on the Principles and spirit and intention of the Code. An advertisement which does or does not adhere to the letter of a particular ethic or guideline nevertheless may or may not be in breach of the Code, depending on its compliance with the Principles and respect of the spirit and intention of the Code. In interpreting standards of advertising of various services there will be reference to the appropriate industry Code of Ethics as it relates to advertising.",
 "Principles": {
  "1": {"Should": "Complies with law",    "ShouldNot": "Breaks <strong>NZ Law</strong>",           "Code": "<p>Advertisements must comply with the laws of New Zealand.</p>"},
  "2": {"Should": "Not misleading",       "ShouldNot": "Is <strong>False</strong> or <strong>Misleading</strong>",    "Code": "<p>Advertisements must be truthful, balanced and not misleading. Claims must be valid and have been substantiated.</p>"},
  "3": {"Should": "Socially Responsible", "ShouldNot": "Is <strong>Socially Irresponsible</strong>", "Code": "<p>Advertisements must observe a high standard of social responsibility.</p>"}},
 "Requirements": {
  "B1": {
   "Title": "Advertising Medicines to Consumers",
   "Requirements": {
    "1":  {"Should": "Promotes proper use only",           "ShouldNot": "Encourages <strong>Inappropriate</strong> or <strong>Excessive</strong> use",     "Code": "<p>Advertisements must not encourage, or be likely to encourage, inappropriate or excessive use.</p>"},
    "2":  {"Should": "Includes responsible use info",      "ShouldNot": "Is missing <strong>Mandatory Use Info</strong>",                   "Code": "<p>Advertisements must contain the mandatory information to encourage responsible use.</p>"},
    "3":  {"Should": "True and Balanced",                  "ShouldNot": "Contains <strong>Untrue</strong> or <strong>Unbalanced</strong> claims",                  "Code": "<p>To assist consumers to make informed decisions, advertisements must contain truthful and balanced representations and claims that are valid and have been substantiated and:<ol class=\"list-style-type:lower-alpha\"><li>for medicines - must be consistent with the indications included on the database of therapeutic products maintained by Medsafe; and</li><li>for exempt therapeutic products - must be compliant with the Code.</li></ol></p>"},
	"4":  {"Should": "Not misleading or scary",            "ShouldNot": "Is <strong>Misleading</strong> or <strong>Distressing</strong>",                    "Code": "<p>Advertisements must not directly nor by implication, omission, ambiguity, exaggerated claim or comparison:<ol class=\"list-style-type:lower-alpha\"><li>mislead or deceive, or be likely to mislead or deceive; or</li><li>abuse trust, or exploit lack of knowledge; or</li><li>exploit the superstitious or, without justifiable reason, play on fear or cause distress.</li></ol></p>", "SubRequirements": {
     "1": {"Should": "Not 100% safe, magical or needed",   "ShouldNot": "Claims to be <strong>100% Safe</strong>, <strong>100% Effective</strong>, <strong>Magical</strong> or <strong>Needed</strong>", "Code": "<p>An advertisement must not:<ol class=\"list-style-type:lower-roman\"><li>contain any claim, statement or implication that the products are safe or that their use cannot cause harm or that they have no side effects or risks associated with use;</li><li>contain any claim, statement or implication that the product is effective in all cases of a condition;</li><li>contain any claim, statement or implication that it is infallible, unfailing, magical, miraculous, or that it is a certain, guaranteed or sure cure;</li><li>contain any matter which is likely to lead persons to believe that; - they<ul><li>are suffering from a serious ailment, or</li><li>harmful consequences may result from the therapeutic product not being used.</li></p>"},
     "2": {"Should": "Fair comparisons to other products", "ShouldNot": "Makes <strong>Unfair Comparisons</strong> to other products",          "Code": "<h3>Comparative advertising</h3><p>Comparative advertising must be balanced and must not be misleading, or likely to be misleading, either about the product advertised or any therapeutic products, or classes of therapeutic products, with which comparison is made.</p><p>Comparative advertisements must not be disparaging but must be factual, fair and already substantiated, referenced to the source and reflective of the body of available evidence.</p><p>In comparing products, advertisements must not discourage consumers from taking therapeutic products prescribed by a healthcare practitioner.</p>"},
     "3": {"Should": "Accurate science",                   "ShouldNot": "Contains <strong>Inaccurate Science</strong>",                           "Code": "<h3>Scientific information</h3><p>Scientific information within an advertisement must be presented in an accurate manner. Scientific terminology must be appropriate, clearly communicated and able to be readily understood by the audience to whom it is directed.</p><p>Publication of research results in an advertisement must identify the researcher and the financial sponsor of the research.</p>"}}},
    "5":  {"Should": "Not glamorising",                    "ShouldNot": "<strong>Glamorises</strong> the product",                                  "Code": "<p>Advertisements must not unduly glamorise products or services, or prey on the vulnerability of particular audiences.</p>"},
    "6":  {"Should": "Verified endorsements",              "ShouldNot": "Contains <strong>Unverified Endorsements</strong>",                      "Code": "<p>Advertisements may include reference to sponsorship of any government agency, hospital or other facility providing healthcare services, provided that sponsorship is explicitly acknowledged and cannot be misconstrued as an endorsement of a product.</p><p>Advertisements may contain or imply an endorsement by individual, or individual groups of, healthcare practitioners in their professional capacity, bodies or associations representing the interests of the health of consumers, conducting or funding medical research or representing health practitioners, provided that the endorsement does not in any way imply endorsement by any government agency, hospital or other facility providing healthcare services. However, such endorsements must have prior consent from the endorser, be authenticated and the advertisement must contain, prominently displayed, the name of the endorser and acknowledgment of any valuable consideration.</p>"},
    "7":  {"Should": "Verified testimonials",              "ShouldNot": "Contains <strong>Unverified Testimonials</strong>",                      "Code": "<p>Testimonials in advertisements, where not prohibited by law, must comply with the Code, be authenticated, genuine, current, typical and acknowledge any valuable consideration.</p>"},
    "8":  {"Should": "Doesn't mention serious ailments",   "ShouldNot": "Mentions <strong>Serious Ailments</strong>",                     "Code": "<p>Advertisements directed to consumers must not refer directly or by implication to serious diseases, conditions, ailments or defects without approval from Medsafe.</p>"}}},
  "B2": {
   "Title": "Advertising Medical Devices to Consumers",
   "Requirements": {
    "1":  {"Should": "Promotes proper use only",           "ShouldNot": "Encourages <strong>Inappropriate</strong> or <strong>Excessive</strong> use",     "Code": "<p>Advertisements must not encourage, or be likely to encourage, inappropriate or excessive use.</p>"},
    "2":  {"Should": "Includes responsible use info",      "ShouldNot": "Is missing <strong>Mandatory Use Info</strong>",                   "Code": "<p>Advertisements must contain the mandatory information to encourage responsible use. Any advertisement for therapeutic products must include all of the required statements in paragraphs (a) to (e), other than where:<ul><li>the advertisement does not contain a therapeutic claim or intended purpose for use and displays only the brand/name/picture of the therapeutic products and/or the price and/or point of sale; or</li><li>the advertisement is an unbranded, or a reminder, or a sponsorship advertisement.</li><li>All required statements in paragraph (a) must be prominently displayed or communicated, i.e. standing out so as to be easily read from a normal viewing distance, and/or heard and understood.</li></ul>Advertisements to consumers for medical devices must contain the following statements:<ul><li>the trade name;</li><li>the intended purpose consistent with that included in the WAND database of medical devices maintained by Medsafe; and</li><li>the following mandatory statement (except where the advertisement is for a health service or treatment program that includes a reference to the use or administration of a particular device as part of that service or treatment):<br />ALWAYS READ THE LABEL<br />and/or, where appropriate,<br />FOLLOW THE INSTRUCTIONS (or words to that effect)</li></ul>If the medical device has contraindications or specific warnings that may affect the safe use of the device, which are reflected in the regulatory requirements for the product label or in the patient information, an appropriate warning must be given.</p>"},
    "3":  {"Should": "True and Balanced",                  "ShouldNot": "Contains <strong>Untrue</strong> or <strong>Unbalanced</strong> claims",                  "Code": "<p>To assist consumers to make informed decisions, advertisements must contain truthful and balanced representations and claims that are valid and have been substantiated and:<ol class=\"list-style-type:lower-alpha\"><li>for medical devices - must be consistent with the manufacturer’s intended purposes included on the WAND database for medical devices maintained by Medsafe; and</li><li>for exempt therapeutic products - must be compliant with the Code.</li></ol></p>"},
    "4":  {"Should": "Not misleading or scary",            "ShouldNot": "Is <strong>Misleading</strong> or <strong>Distressing</strong>",                    "Code": "<p>Advertisements must not directly nor by implication, omission, ambiguity, exaggerated claim or comparison:<ol class=\"list-style-type:lower-alpha\"><li>mislead or deceive, or be likely to mislead or deceive; or</li><li>abuse trust, or exploit lack of knowledge; or</li><li>exploit the superstitious or, without justifiable reason, play on fear or cause distress.</p>", "SubRequirements": {
	 "1": {"Should": "Not 100% safe, magical or needed",   "ShouldNot": "Claims to be <strong>100% Safe</strong>, <strong>100% Effective</strong>, <strong>Magical</strong> or <strong>Needed</strong>", "Code": "<p>An advertisement must not:<ol class=\"list-style-type:lower-roman\"><li>contain any claim, statement or implication that the products are safe or that their use cannot cause harm or that they have no side effects or risks associated with use;</li><li>contain any claim, statement or implication that the product is effective in all cases of a condition;</li><li>contain any claim, statement or implication that it is infallible, unfailing, magical, miraculous, or that it is a certain, guaranteed or sure cure;</li><li>contain any matter which is likely to lead persons to believe that;<ul><li>they are suffering from a serious ailment, or</li><li>harmful consequences may result from the therapeutic product not being used.</li></ul></ol></p>"},
     "2": {"Should": "Fair comparisons to other products", "ShouldNot": "Makes <strong>Unfair Comparisons</strong> to other products",          "Code": "<h3>Comparative advertising</h3><p>Comparative advertising must be balanced and must not be misleading, or likely to be misleading, either about the product advertised or any therapeutic products, or classes of therapeutic products, with which comparison is made.</p><p>Comparative advertisements must not be disparaging but must be factual, fair and already substantiated, referenced to the source and reflective of the body of available evidence.</p><p>In comparing products, advertisements for medical devices must only make comparisons between products with a similar intended purpose of use.</p>"},
     "3": {"Should": "Accurate science",                   "ShouldNot": "Contains <strong>Inaccurate Science</strong>",          "Code": "<h3>Scientific information</h3><p>Scientific information within an advertisement must be presented in an accurate manner. Scientific terminology must be appropriate, clearly communicated and able to be readily understood by the audience to whom it is directed.</p><p>Publication of research results in an advertisement must identify the researcher and the financial sponsor of the research.</p>"}}},
    "5":  {"Should": "Not glamorising",                    "ShouldNot": "<strong>Glamorises</strong> the product",                                  "Code": "<p>Advertisements must not unduly glamorise products or services, or prey on the vulnerability of particular audiences.</p>"},
    "6":  {"Should": "Verified endorsements",              "ShouldNot": "Contains <strong>Unverified Endorsements</strong>",                      "Code": "<p>Advertisements may include reference to sponsorship of any government agency, hospital or other facility providing healthcare services, provided that sponsorship is explicitly acknowledged and cannot be misconstrued as an endorsement of a product.</p><p>Advertisements may contain or imply an endorsement by individual, or individual groups of, healthcare practitioners in their professional capacity, bodies or associations representing the interests of the health of consumers, conducting or funding medical research or representing health practitioners, provided that the endorsement does not in any way imply endorsement by any government agency, hospital or other facility providing healthcare services. However, such endorsements must have prior consent from the endorser, be authenticated and the advertisement must contain, prominently displayed, the name of the endorser and acknowledgment of any valuable consideration.</p>"},
    "7":  {"Should": "Verified testimonials",              "ShouldNot": "Contains <strong>Unverified Testimonials</strong>",                      "Code": "<p>Testimonials in advertisements, where not prohibited by law, must comply with the Code, be authenticated, genuine, current, typical and acknowledge any valuable consideration.</p>"},
    "8":  {"Should": "Doesn't say experts only",           "ShouldNot": "Mentions <strong>Serious Ailments</strong>",                     "Code": "<p>Advertisements directed to consumers must not refer directly or by implication to medical devices, or procedures involving medical devices, that are intended to be used and/or administered solely by healthcare practitioners, without approval from Medsafe.</p>"}}},
   "B3": {
   "Title": "Advertising Directed to Healthcare Practitioners",
   "Preface": "<p>The Advertising Principles and relevant Advertising Requirements included in this part of the Code apply specifically to advertisements for therapeutic products that are directed to healthcare practitioners.</p><p>PART A of the Code applies to the advertising of therapeutic products directed both to consumers and to healthcare practitioners.</p><p>All advertising directed to healthcare practitioners must encourage the responsible and quality use of therapeutic products. Because healthcare practitioners have expert and professional knowledge in their relevant fields, and are able to discriminate between information of value and advertising hyperbole, not all of the Advertising Requirements in Sections B1 and B2 (i.e. advertising directed to consumers) apply.</p><p>The following requirements for advertising to healthcare practitioners have been developed by the relevant industry associations in New Zealand with reference to their existing codes of practice. These requirements will continue to be reflected in the industry association codes. Where applicable, the requirements are the same as those for advertising to consumers.</p><p>While this Code sets the minimum standard for advertising requirements, additional requirements may be applied to particular industry sectors through the industry association codes. These additional requirements can be found in the individual industry association codes, which also provide additional guidance on the application of these requirements.</p>",
   "Requirements": {
    "1":  {"Should": "Promotes proper use only",           "ShouldNot": "Encourages <strong>Inappropriate</strong> or <strong>Excessive</strong> use", "Code": "<p>Advertisements must not encourage, or be likely to encourage, inappropriate or excessive use.</p>"},
    "2":  {"Should": "Includes responsible use info",      "ShouldNot": "Is missing <strong>Mandatory Use Info</strong>",               "Code": "<p>Advertisements must contain the mandatory information to ensure responsible use.</p>"},
    "3":  {"Should": "True and Balanced",                  "ShouldNot": "Contains <strong>Untrue</strong> or <strong>Unbalanced</strong> claims",              "Code": "<p>Advertisements must contain truthful and balanced representations and claims that are valid and have been substantiated, and:<ol class=\"list-style-type:lower-alpha\">for medicines:<br />must be consistent with the approved Product Information, or other substantiation of efficacy provided by the sponsor to Medsafe;</li><li>for medical devices:<br />must be consistent with the manufacturer’s intended purposes, included on the WAND database for medical devices maintained by Medsafe; and</li><li>for exempt therapeutic products:<br />must be compliant with this Code.</p>"},
    "4":  {"Should": "Not misleading",                     "ShouldNot": "Is <strong>Misleading</strong>",                               "Code": "<p>Advertisements must not directly nor by implication, omission, ambiguity or comparison mislead or deceive, or be likely to mislead or deceive.</p><p>Claims and representations made in advertisements must be truthful and have been substantiated.</p>", "SubRequirements": {
     "1": {"Should": "Not 100% safe or magical",           "ShouldNot": "Claims to be <strong>100% Safe</strong>, <strong>100% Effective</strong> or <strong>Magical</strong>",     "Code": "<p>An advertisement must not:<ol class=\"list-style-type:lower-roman\"><li>contain any claim, statement or implication that the products are safe or that their use cannot cause harm or that they have no side effects or risks associated with use;</li><li>contain any claim, statement or implication that it is effective in all cases of a condition;</li><li>contain any claim, statement or implication that it is infallible, unfailing, magical, miraculous, or that it is a certain, guaranteed or sure cure;</li></ol></p>"},
     "2": {"Should": "Fair comparisons to other products", "ShouldNot": "Makes <strong>Unfair Comparisons</strong> to other products",      "Code": "<h3>Comparative advertising</h3><p>Comparative advertising must be balanced and must not be misleading, or likely to be misleading, either about the product advertised or any therapeutic products, or classes of therapeutic products, with which comparison is made.</p><p>Comparative advertisements must not be disparaging but must be factual, fair and already substantiated, referenced to the source and reflective of the body of available evidence.</p>"},
     "3": {"Should": "Supporting data",                    "ShouldNot": "Lack Supporting Data",                     "Code": "<h3>Substantiating Data</h3>Any information used to support a claim must include sufficient detail, and be of adequate quality, to allow evaluation of the validity of results and hence of the claim.</p>"}}},
    "5":  {"Should": "Not glamorising",                    "ShouldNot": "<strong>Glamorises</strong> the product",                              "Code": "<p>Advertisements must not unduly glamorize products or services.</p>"},
    "6":  {"Should": "Verified endorsements",              "ShouldNot": "Contains <strong>Unverified Endorsements</strong>",                  "Code": "<p>Advertisements may include reference to sponsorship of any government agency, hospital or other facility providing healthcare services, provided that sponsorship is explicitly acknowledged and cannot be misconstrued as an endorsement of a product.</p><p>Advertisements may contain or imply an endorsement by individual, or individual groups of, healthcare practitioners in their professional capacity, bodies or associations representing the interests of the health of consumers, conducting or funding medical research or representing health practitioners, provided that the endorsement does not in any way imply endorsement by any government agency, hospital or other facility providing healthcare services. However, such endorsements must have prior consent from the endorser, be authenticated and the advertisement must contain, prominently displayed, the name of the endorser and acknowledgment of any valuable consideration. Industry codes of practice address appropriate transparency requirements in relation to the funding of research by sponsors.</p>"},
    "7":  {"Should": "Verified testimonials",              "ShouldNot": "Contains <strong>Unverified Testimonials</strong>",                  "Code": "<p>Testimonials in advertisements, where not prohibited by law, must comply with the Code, be authenticated, genuine, current, typical and acknowledge any valuable consideration. The use of testimonials in advertisements to promote therapeutic products is acceptable, provided the testimonial:<ul><li>is genuine;</li><li>complies with the Code;</li><li>is current;</li><li>has been authenticated; and</li><li>presents the typical case, not the exceptional.</li></ul></p><p>\"Current\" means that the content of a testimonial must be up to date and hold true at the time of the publication of the advertisement.</p><p>\"Typical\" means that which reflects the characteristics of a group. i.e. a result obtained from the use of a product which would be likely to be attained by most people using the product within the audience to which the advertisement is directed.</p>"},
    "9":  {"Should": "Only approved claims made",          "ShouldNot": "Makes <strong>Unapproved Claims</strong>",                        "Code": "<h3>Medicines<p>All communications made by company representatives must comply with the Code. Where the product being advertised is a finished product, therapeutic claims for unlicensed products and unapproved indications must not be made, unless the product is exempt from product licensing.</p><p>Whenever a therapeutic claim is made for a product for which the sponsor is required to hold a product licence, a company representative must offer the approved PI, or other data used by the sponsor as the basis for obtaining the product licence for the product.</p><p>Whenever a therapeutic claim is made for:<ul><li>an active ingredient that may be used in the manufacture of therapeutic products; or</li><li>a product which is exempt from product licensing;</li></ul>the data used by the supplier to verify the claim must be offered by the company representative. Advertisements directed to healthcare practitioners for extemporaneously compounded therapeutic products (as finished goods which are exempt from product licensing) are required to comply with the Code.</p><h3>Medical Devices</h3><p>The representation of medical devices/diagnostics included on the database for therapeutic products maintained by Medsafe must be consistent with the manufacturer’s intended purposes and be consistent with the essential principles for the product.</p><p>When requested, the representative must be able to supply a copy of the sponsor's product information consistent with the manufacturer's intended purpose and essential principles.</p><p>Claims outside the manufacturer's intended purpose and essential principles must not be made.</p><p>For non-therapeutic claims the sponsor must hold substantiating data to support the claims.</p>"}}}}},
"ts": {
 "Title": "Therapeutic Services",
 "Hint": "e.g. Acupuncture or Reiki",
 "URL": "http://www.asa.co.nz/code_therapeutic_services.php",
 "Introduction": "All advertisements for therapeutic services (herein called \"therapeutic services\") shall adhere to the Principles and Guidelines set out in this Code. The Code is designed to ensure that advertising for such services will be conducted in a manner which is socially responsible and does not mislead or deceive the consumer. Other ASA Codes may also be relevant.In interpreting the Code emphasis will be placed on the Principles and spirit and intention of the Code. An advertisement which does or does not adhere to the letter of a particular ethic or Guideline nevertheless may or may not be in breach of the Code, depending on its compliance with the Principles and respect of the spirit and intention of the Code.In interpreting standards of advertising of various services there will be reference to the appropriate industry Code of Ethics as it relates to advertising.",
 "Principles": {
  "1":  {"Should": "Complies with NZ law and code of ethics", "ShouldNot": "Breaks <strong>NZ Law</strong> or <strong>Code of Ethics</strong>", "Code": "<p>Advertisements should comply with the laws of New Zealand and the appropriate industry Code of Ethics.</p>"},
  "2":  {"Should": "Socially Responsible",                    "ShouldNot": "Is <strong>Socially Irresponsible</strong>",         "Code": "<p>Advertisements should observe a high standard of social responsibility particularly as consumers rely on therapeutic services for their health and well-being.</p>"},
  "3":  {"Should": "Not misleading or scary",                 "ShouldNot": "Is <strong>Misleading</strong> or <strong>Distressing</strong>",      "Code": "<p>Advertisements should not by implication, omission, ambiguity or exaggerated claim mislead or deceive or be likely to mislead or deceive consumers, abuse the trust of or exploit the lack of knowledge of consumers, exploit the superstitious or without justifiable reason play on fear.</p>", "Guidelines": {
   "a": {"Should": "Factual",                                 "ShouldNot": "Contains <strong>Untrue</strong> or <strong>Unproven</strong> claims",      "Code": "<p>Therapeutic claims should be factual and able to be proved.</p>"},
   "b": {"Should": "Not glamorising",                         "ShouldNot": "<strong>Glamorises</strong> the service",                    "Code": "<p>Advertisements should not have depictions which unduly glamorise the service or portray unrealistic outcomes.</p>"}}},
  "4":  {"Should": "Accurate science",                        "ShouldNot": "Contains <strong>Inaccurate Science</strong>",             "Code": "<p>Any scientific information in an advertisement should be presented in an accurate manner. Scientific terminology should be appropriate, clearly communicated and able to be readily understood by the audience to whom it is directed.</p>"},
  "5":  {"Should": "Verified endorsements",                   "ShouldNot": "Contains <strong>Unverified Endorsements</strong>",        "Code": "<p>Advertisements should not claim or imply endorsement by any government agency, professional body or independent agency unless there is prior consent, the endorsement is verifiable and the agency or the body is named.</p>", "Guidelines": {
   "a": {"Should": "Verified testimonials",                   "ShouldNot": "Contains <strong>Unverified Testimonials</strong>",        "Code": "<p>Testimonials, where not prohibited by law, should be valid, true, current, documented and exceptional cases should be represented as such, not as typical. The claims in testimonials should be verifiable.</p>"}}}}},
"wm": {
 "Title": "Weight Management",
 "Hint": "e.g. a Diet Pill or Drink",
 "URL": "http://www.asa.co.nz/code_weight.php",
 "Introduction": "<p>All advertisements for weight management shall adhere to the Principles and Guidelines set out in this Code. The purpose of the Code is to ensure that advertising of weight management goods or services will be conducted in a manner which is socially responsible and does not mislead or deceive the consumer.</p><p>In interpreting the Code emphasis will be placed on the Principles and the spirit and intention of the Code. An advertisement which does or does not adhere to the letter of a particular Guideline nevertheless may or may not be in breach of the Code, depending on its compliance with the Principles and respect of the spirit and intention of the Code.</p><p>This Code applies to weight management products (including services) which include nutrition and exercise as features.</p><p>The Code does not apply to advertisements with therapeutic claims that advertise medicines, dietary supplements or medical devices; in those cases the Code for Therapeutic Advertising applies.</p>",
 "Principles": {
  "1":  {"Should": "Complies with law and industry standards",      "ShouldNot": "Breaks <strong>NZ Law</strong> or <strong>Industry Standards</strong>",     "Code": "<p>Advertisements should comply with the laws of New Zealand and appropriate industry standards.</p>", "Guidelines": {
   "a": {"Should": "Complies with specific laws",                   "ShouldNot": "Breaks <strong>Medicine</strong>, <strong>Food</strong> or <strong>Diet</strong> Acts",      "Code": "<p>There are a number of laws which can affect slimming or weight loss advertising. Attention is drawn to the Medicines Act 1981, Medicines Regulations 1984, Food Act 1981, Food Regulations 1984 and the Dietary Supplement Regulations 1985.</p>"},
   "b": {"Should": "Altering shape, structure, size or weight",     "ShouldNot": "Claims to alter Shape, Structure, Size or Weight", "Code": "<p>Particular attention is drawn to Section 4(e) of the Medicines Act 1981 which includes in the definition of 'therapeutic purpose' \"Altering the shape, structure, size or weight of the human body\". The effect of this is that a food, tablet or substance which reduces weight is classified as a \"medicine\" and an apparatus as a \"medical device\", thus bringing them within the ambit of the Medicines Act 1981. In such cases the Code for Therapeutic Advertising applies. Weight reduction programmes may not be subject to the Medicines Act 1981, but are subject to this Code. Advice from the Therapeutic Advertising Pre-vetting Services (TAPS) is strongly recommended.</p>"}}},
  "2":  {"Should": "Socially Responsible",                          "ShouldNot": "Is <strong>Socially Irresponsible</strong>",                 "Code": "<p>Advertisements should observe a high standard of social responsibility.</p>", "Guidelines": {
   "a": {"Should": "Well-balanced and over 800 calories",           "ShouldNot": "Suggests a diet that is <strong>Unbalanced</strong> or under <strong>800 Calories</strong>",  "Code": "<p>Advertisements should not suggest or imply that consumers should have a diet which is not nutritionally well-balanced nor advertise a diet plan with less that 3500 kilojoules (800 calories) per day.</p>"},
   "b": {"Should": "Realistic and Safe",                            "ShouldNot": "Suggests <strong>Unrealistic</strong> or <strong>Unsafe</strong> weight loss",      "Code": "<p>Advertisements should not promise unrealistic or unsafe rapid weight reduction.</p>"},
   "c": {"Should": "18 and over",                                   "ShouldNot": "Is directed at <strong>Under 18s</strong>", "Code": "<p>Advertisements should neither be directed at, nor have strong or evident appeal to people under the age of 18 in particular.</p>"},
   "d": {"Should": "Average models",                                "ShouldNot": "Uses <strong>Underweight Models</strong>", "Code": "<p>Advertisements should not suggest that it is desirable to be underweight or use underweight models. Models of generally accepted height/weight ratios should be used.</p>"},
   "e": {"Should": "See doctor before exercise",                    "ShouldNot": "", "Code": "<p>Advertisements for intensive exercise programmes should encourage users to check with a doctor or professional advisor before commencing.</p>"},
   "f": {"Should": "Not a substitute for a balanced diet",          "ShouldNot": "Claims to be a <strong>Substitute for a Balanced Diet</strong>", "Code": "<p>Advertisements should not imply that the advertised product is a substitute for a balanced diet.</p>"}}},
  "3":  {"Should": "Not misleading or scary",                       "ShouldNot": "Is <strong>Misleading</strong> or <strong>Distressing</strong>", "Code": "<p>Advertisements should not by implication, omission, ambiguity or exaggerated claim, mislead or deceive or be likely to mislead or deceive consumers, abuse the trust of or exploit the lack of knowledge of consumers, exploit the superstitious or without justifiable reason play on fear.</p>", "Guidelines": {
   "a": {"Should": "Typical, realistic, factual and proven claims", "ShouldNot": "Makes <strong>Atypical</strong>, <strong>Unrealistic</strong>, <strong>False</strong> or <strong>Unproven</strong> claims", "Code": "<p>Claims for specific weight loss or reduction in body measurement should be typical, realistic, factual and able to be proved.</p>"},
   "b": {"Should": "Not glamorising",                               "ShouldNot": "<strong>Glamorises</strong> the product", "Code": "<p>Advertisements should not have depictions which unduly glamorise the product or portray unrealistic outcomes.</p>"},
   "c": {"Should": "Not saying eat to diet",                        "ShouldNot": "Claims the ability to <strong>Eat to Lose Weight</strong>", "Code": "<p>Claims such as \"Eat as much as you like\", \"Eat, eat, eat\" or \"Eat and get slim\" are unacceptable.</p>"}}},
  "4":  {"Should": "Verified endorsements",                         "ShouldNot": "Contains <strong>Unverified Endorsements</strong>", "Code": "<p>Advertisements should not claim or imply endorsement by any government agency, professional body, independent agency or person unless there is prior consent and the endorsement verifiable.</p>", "Guidelines": {
   "a": {"Should": "Verified testimonials",                         "ShouldNot": "Contains <strong>Unverified Testimonials</strong>", "Code": "<p>Testimonials, where not prohibited by law should be valid, current, documented and exceptional cases should be represented as such, not as typical. The claims in testimonials should be verifiable.</p>"}}}}}};

$(function() {
 var section;
 $("#asa").replaceWith('<form id="asa"><fieldset id="code"><legend>Complaint type</legend></fieldset></form>');
 $.each( ASACodes, function(codeKey, Code) {
  $("#code").append('<input class="radio" type="radio" name="code" value="' + codeKey + '" title="' + Code.Hint + '">' + Code.Title + '</input><br />');
  $("#asa").append('<div id="' + codeKey + '"><h2><a href="' + Code.URL + '" target="_blank">' + Code.Title + '</a></h2><fieldset id="' + codeKey + 'p" class="hidden"><legend>Principles</legend><h3>Please select if the advert:</h3></fieldset></div>');
  $.each(Code.Principles, function(principleNumber, Principle) {
   section = "Principle " + principleNumber;
   $("#" + codeKey + "p").append('<input type="checkbox" name="' + codeKey + "p" + '" value="' + section + '" title="' + section + '">' + Principle.ShouldNot + '</input><br />');
   if (typeof(Principle.Guidelines) != "undefined")
   {
    $.each(Principle.Guidelines, function(guidelineLetter, Guideline) {
     section = "Principle " + principleNumber + ", Guideline " + guidelineLetter;
     $("#" + codeKey + "p").append('&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="' + codeKey + "p" + '" value="' + section + '" title="' + section + '">' + Guideline.ShouldNot + '</input><br />');
    });
   }
  });
  if (typeof(Code.Requirements) != "undefined")
  {
   $.each(Code.Requirements, function(sectionCode, Section) {
    $("#" + codeKey).append('<fieldset id="' + codeKey + 'r' + sectionCode + '"><legend>Requirements</legend></fieldset>');
    $.each(Section.Requirements, function(requirementNumber, Requirement) {
     section = "Part " + sectionCode + ", Requirement " + requirementNumber;
     $("#" + codeKey + "r" + sectionCode).append('<input type="checkbox" name="' + codeKey + "r" + sectionCode + '" value="' + section + '" title="' + section + '">' + Requirement.ShouldNot + '</input><br />');
     if (typeof(Requirement.SubRequirements) != "undefined")
     {
      $.each(Requirement.SubRequirements, function(subRequirementNumber, SubRequirement) {
       section = "Part " + sectionCode + ", Requirement " + requirementNumber + '.' + subRequirementNumber;
       $("#" + codeKey + "r" + sectionCode).append('&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="' + codeKey + "r" + sectionCode + '" value="' + section + '" title="' + section + '">' + SubRequirement.ShouldNot + '</input><br />');
      });
     }
    });
   });
  }
 });
});